services:

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file: 
     - .env
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
     - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx:
    build: 
     context: .
     dockerfile: ./etc/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf