
export const buildTransferMarkdown = (transactions: [], currentPriceInUSD: number)=>{
    let markdown = '';

    
    if(transactions.length > 0)
           
          markdown += '**Generated by Myafros**\n\n'
          const sortedByFrom = transactions.sort((a: any, b:any)=>b.from - a.from)

         

          const sortedTransactions = transactions.sort((a: any, b: any) => b.timeStamp - a.timeStamp);
          sortedTransactions.forEach((tx : any) => {
            markdown += `
     
                - **Date:** ${new Date(tx.timeStamp * 1000).toLocaleString()}
                - **Hash:** ${tx.hash}
                - **From:** ${tx.from}
                - **To:**   ${tx.to}
                - **Value:** ${(tx.value / 1e18).toFixed(8)} ETH
                - **Historical Value in USD:** $${(0.00).toFixed(2)}
                - **Current Value in USD:** $${((tx.value / 1e18) * currentPriceInUSD).toFixed(2)}
            `;
        });


    return markdown
}